<?php

class Ortu
{
    protected $nama;

    public function __construct($nama)
    {
        $this->nama = $nama;
        echo $this->nama . " Dilahirkan <br>";
    }

    public function kehidupan()
    {
        echo $this->nama . " sedang menjalani kehidupan<br>";
    }

    public function __destruct()
    {
        echo $this->nama . " meninggal...<br>";
    }
}

class Anak extends Ortu
{
    public function __construct($nama)
    {
        parent::__construct($nama);
        echo $this->nama. " Dilahirkan (constructor anak) <br>";
    }

    public function __destruct()
    {
        echo $this->nama. " Sakit...<br>";
        parent::__destruct(); // TODO: Change the autogenerated stub
    }
}

$ortu = new Ortu("Udin");
$ortu->kehidupan();
echo "Proses lain..<br><br>";
$anak = new Anak("Putra");
$anak->kehidupan();
